# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
install:
    - sudo R CMD javareconf
sudo: required

